name: Deploy RSPress Docs

on:
  push: {}  # ✅ 모든 브랜치에서 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm --filter ./docs... rspress build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # ✅ 실제 배포는 main일 때만
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist
