name: Build & Deploy Docs

on:
  push: {}                              # 모든 브랜치

permissions:                            # ← 필수! contents:write
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4      # version 지정 X (package.json에 있음)

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build docs
        run: cd docs && pnpm rspress build         # 결과: docs/dist

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../docs/doc_build        # ← 존재 확정
